### ISSUE TITLE
Support EntityManager

### ISSUE THREAD

**Issue by muglug** [weirdan/doctrine-psalm-plugin#1]
If you can point me in the general direction of how to do this (e.g. an open-source codebase that would benefit from this typing) I can create a PR

**Comment by weirdan** [comment]
@muglug 
I'm not familiar with any open-source projects using Doctrine. We use it, however, in house, so would benefit from better psalm support.

I've added `EntityManager`, `EntityRepository` and `Paginator` stubs, see if that covers what you might've wanted to add. Feel free to submit PRs :)

**Comment by muglug** [comment]
Awesome, thanks!
