### ISSUE TITLE
Taint Sink connection->executeStatement is missing

### ISSUE THREAD

**Issue by timglabisch** [weirdan/doctrine-psalm-plugin#104]
the taint sink for the function `executeStatement` is missing (the deprecated `exec` works).

example:
`$connection->executeStatement('sql '. $request->get('foo'));` 

https://github.com/psalm/psalm-plugin-doctrine/blob/b24dcfd4815eed489800e97c0b605932800aabec/stubs/Connection.phpstub#L52

**Comment by orklah** [comment]
Seems coherent. Mind proposing a PR?
