### ISSUE TITLE
Bug: One-off declarations on @psalm-params for Connection::executeUpdate && Connection::executeStatement

### ISSUE THREAD

**Issue by martinsebastianwns** [weirdan/doctrine-psalm-plugin#106]
@psalm-param definitions for $query and $types are off by one on executeUpdate and executeStatement.

**Connection::executeUpdate**

https://github.com/psalm/psalm-plugin-doctrine/blob/089d10e0022609df55ca85a17f66261662a37751/stubs/Connection.phpstub#L63

https://github.com/psalm/psalm-plugin-doctrine/blob/089d10e0022609df55ca85a17f66261662a37751/stubs/Connection.phpstub#L64

**Connection::executeStatement**

https://github.com/psalm/psalm-plugin-doctrine/blob/089d10e0022609df55ca85a17f66261662a37751/stubs/Connection.phpstub#L72

https://github.com/psalm/psalm-plugin-doctrine/blob/089d10e0022609df55ca85a17f66261662a37751/stubs/Connection.phpstub#L73

---

**Proposal:**
```
-     * @psalm-param scalar[]        $params The query parameters.
+     * @psalm-param scalar[]        $query The query parameters.
-     * @psalm-param int[]|string[]  $types  The parameter types.
+     * @psalm-param int[]|string[]  $params  The parameter types.

public function [...](string $query, array $params = [], array $types = []): int {}
```

---

**Error Output:**

```
 Argument 2 of Doctrine\DBAL\Connection::executeUpdate expects array<array-key, scalar>, array{ids: array<array-key, mixed>} provided (see https://psalm.dev/004)
            array(
                'ids' => $articleIDs
            ),
```

BR
Martin

**Comment by orklah** [comment]
The error you get is because you're trying to push `mixed[]` to  `$params`. I don't expect your proposal to make it any better. Replacing `scalar[]` by `int[]|string[]` restricts the type even more

**Comment by martinsebastianwns** [comment]
Heya @orklah, thank you for the correction. You are absolutely correct.

**Comment by weirdan** [comment]
> definitions for $query and $types are off by one

Psalm matches params to docblock tags by parameter name.

**Comment by orklah** [comment]
small error on my part, you didn't push `mixed[]` but `array<string, mixed[]>` but the conclusion was the same

**Comment by martinsebastianwns** [comment]
> > definitions for $query and $types are off by one
> 
> Psalm matches params to docblock tags by parameter name.

I know. I mixed it up when reading the param descriptions, the words "query" and "parameter" came off very prominent to me but the rest is history.

**Comment by spideyfusion** [comment]
Actually, we're getting hit with the same problem. I think that the updated stub introduced in https://github.com/psalm/psalm-plugin-doctrine/pull/105 is incorrect, as the following code is perfectly valid, yet Psalm is complaining:

```php
$this->entityManager->getConnection()->executeStatement($sql, [$uuids], [Connection::PARAM_STR_ARRAY]);
```

results in:

```sh
ERROR: InvalidArgument - some/path/Service.php:621:13 - Argument 2 of Doctrine\DBAL\Connection::executeStatement expects array<array-key, scalar>, array{int, array<array-key, mixed>} provided (see https://psalm.dev/004)
            [$uuids],
```

---

The doc block for the `$params` argument on the `executeStatement` method is:

```php
@param array<int, mixed>|array<string, mixed> $params Statement parameters
```

Shouldn't the stub's parameter be `mixed[]` instead of `scalar[]` then?

**Comment by orklah** [comment]
`scalar[]|scalar[][]` would probably be more helpful for users I think

Can you propose a PR?
