### ISSUE TITLE
Cannot load stubs due to an extra '\' in Plugin.php

### ISSUE THREAD

**Issue by Alexander882** [weirdan/doctrine-psalm-plugin#12]
Hi, I'm unable to load the stubs due to the glob in Pluing.php line 22 having two backslashes before the `.php`. It works if I remove the extra slash.

**Comment by weirdan** [comment]
@Alexander882 thanks for ticketing. I think that change should fix the issue, new point release should be available shortly.

**Comment by Alexander882** [comment]
Ah, sorry I forgot to include my environment. It's PHP 7.2 on a Windows 10 machine. Anyways thanks for the fix!
