### ISSUE TITLE
How to handle PhpStorm "Multiple definitions exist for class"?

### ISSUE THREAD

**Issue by ndench** [weirdan/doctrine-psalm-plugin#18]
After installing this plugin, PhpStorm complains that multiple definitions exist for each class stub defined. Because it can't tell whether it should be using the stub.

I can't seem to find a way to make PhpStorm handle this proprly, there's an [SO question](https://stackoverflow.com/questions/23066665/multiple-definitions-exist-for-class) and a [JetBrains issue](https://youtrack.jetbrains.com/issue/WI-17646) for it too.

I'm wondering what everyone else does to deal with this?

**Comment by weirdan** [comment]
I think you could just ignore `vendor/weirdan/doctrine-psalm-plugin/stubs/` in PhpStorm entirely.

**Comment by ndench** [comment]
I did that, it's marked as excluded but so if everything else in `vendor/`. That's how PhpStorm excludes them from search by default unless you specifically say you want to search "everywhere".

**Comment by weirdan** [comment]
And did that help with your issue?

**Comment by ndench** [comment]
No it didn't  Sorry, I should have been more specific. All my vendor packages are already excluded in PhpStorm and I still get the issue.

If I search for a class `EntityManagerInterface` it will only show non-excluded classes (ie. Classes I have defined in my project), unless I tell it to include excluded directories in the search. 

But when typing a parameter as `EntityManagerInterface` PhpStorm will find it by the namespace, regardless of exclusion. 

I can't seem to find a way to say "ignore this directory completely".

**Comment by weirdan** [comment]
[PHPStorm help page](https://www.jetbrains.com/help/phpstorm/excluding-files-from-project.html) says you may want to mark those files as plain text:

> Sometimes you might need to exclude a single file from your project, so that **it will be ignored by** inspections, **code completion**, and so on. This is done using the Mark as plain text action.
>
> When a file is marked as plain text, **PhpStorm does not use it anymore for code completion and navigation**.

**Comment by ndench** [comment]
Oops, sorry I completely forgot about this @weirdan. That actually does work, I was trying to do the "exclude files and folders by name patters" at the bottom of that article. But if I mark each stub as plain text that solves the problem too. 

Thanks!
