### ISSUE TITLE
_WhereExpr type doesn't include all possible Expr classes

### ISSUE THREAD

**Issue by jaikdean** [weirdan/doctrine-psalm-plugin#27]
I've just updated to 0.7.0 and am getting errors reporting when passing `Doctrine\ORM\Query\Expr\Comparison` objects into `Doctrine\ORM\QueryBuilder::andWhere()`.

The `QueryBuilder` stub defines a custom Psalm type `@psalm-type _WhereExpr=Expr\Base|string`. Unfortunately Doctrine's expression classes don't all extend `Doctrine\ORM\Query\Expr\Base`.

I believe the type needs changing to `@psalm-type _WhereExpr=Expr\Base|Expr\Comparison|string`.

**Comment by weirdan** [comment]
Released in [0.7.1](https://github.com/weirdan/doctrine-psalm-plugin/releases/tag/0.7.1). Thanks for reporting!
