### ISSUE TITLE
change T[] to list<T>

### ISSUE THREAD

**Issue by orklah** [weirdan/doctrine-psalm-plugin#33]
Hi,

According to https://psalm.dev/docs/annotating_code/type_syntax/array_types/ , the "list<Foo>" type is a subtype of "array<int, Foo>" with the extra propery that "$arr === array_values($arr)"

Meanwhile, Foo[] is equivalent to array<int|string, Foo>

I believe every case of T[] in the context of Doctrine could be better represented by list<T>

I can try to create the PR if needed.

**Comment by weirdan** [comment]
Hi. I pretty sure some of those could be replaced with `list<T>`, so PR is welcome.

**Comment by orklah** [comment]
Continuing in #34. Closing the issue.
