### ISSUE TITLE
Stubbing Expr class

### ISSUE THREAD

**Issue by jaikdean** [weirdan/doctrine-psalm-plugin#4]
We use the `Doctrine\ORM\Query\Expr` methods in a few places when building queries. Some of these, such as `orX()` and `andX()` accept arbitrary numbers of arguments using `func_get_args()`. The causes the following error when analysing with Psalm.

```
ERROR: TooManyArguments - src/Repository/UserJournalEntryRepository.php:41:17 - Too many arguments for method Doctrine\ORM\Query\Expr::orX - expecting 1 but saw 2
                $qb->expr()->orX(
                    $qb->expr()->gt('uje.value.amount', '0'),
                    $qb->expr()->isNotNull('t')
                )
```

Is it possible to stub these methods? I'm happy to create a PR but don't know how to correctly annotate methods which accept arbitrary numbers of arguments.

**Comment by weirdan** [comment]
I *think* declaring them in the stub as 
```php
    /**
     * @param Expr\Comparison|Expr\Func|Expr\Orx|string ...$x 
     */
    public function andX(...$x): Expr\AndX {}
```
should suffice. Gonna experiment with this later today. It would allow to drop tons of suppressions over here.

**Comment by weirdan** [comment]
@jaikdean Please try with latest master (`composer require --dev weirdan/doctrine-psalm-plugin:dev-master`), seems to be working for me.

**Comment by jaikdean** [comment]
Beautiful, that works here 👍

**Comment by weirdan** [comment]
Great!

**Comment by weirdan** [comment]
I've just pushed a new release containing this fix.
