### ISSUE TITLE
Stubbing DBAL QueryBuilder

### ISSUE THREAD

**Issue by mpolyakovsky** [weirdan/doctrine-psalm-plugin#42]
Just wondering if there's any reason we do have stub for ORM QueryBuilder but don't have one for DBAL?

I could create one unless I miss something, just let me know.

**Comment by weirdan** [comment]
Mostly because ORM QB support was contributed by an interested party (#26) and DBAL hasn't been yet :man_shrugging: 

Feel free to take a stab at it.

**Comment by weirdan** [comment]
Fixed in #45
