### ISSUE TITLE
Change extension to avoid polluting PHPStorm autocompletion

### ISSUE THREAD

**Issue by orklah** [weirdan/doctrine-psalm-plugin#43]
Hi,

This issue was solved by manual configuration in #18 but it could be nice to deal with it for everybody at once.

PHPStan made the choice of renaming their stubs to .stub to solve this issue(https://github.com/phpstan/phpstan-src/commit/b20d7b626132a87f98987cfabb3f55eda5558e76). I think it's a great solution.

Could it be applied here as well?

Thanks

**Comment by weirdan** [comment]
> I think it's a great solution.

Reminds me of all those IE6 hacks actually. I'm willing to help people with their IDE issues, but not at the cost of my own convenience, which would be hampered by changing the extension. If there's a way to make PHPStorm ignore those files by adding some kind of `.gitignore`-like file (perhaps `.idea` folder can be added, dunno if PHPStorm reads those in `vendor` though) I will accept the PR.

**Comment by orklah** [comment]
> Reminds me of all those IE6 hacks actually. 

😄 I kinda hoped it could become a sort of standard, The issue is the same with Symfony's polyfill too, which lead to all sorts of issues (https://github.com/symfony/polyfill/issues/182) and people using obscure composer commands to avoid downloading the packages entirely (https://ayesh.me/composer-replace-polyfills)

> not at the cost of my own convenience, which would be hampered by changing the extension. 

Do you know that, if you use PHPStorm, you can add any extension to the list of file that must be read as PHP? It will then behave exactly as if the file was a PHP file. However, I understand you may not want to bother.

> If there's a way to make PHPStorm ignore those files by adding some kind of `.gitignore`-like file (perhaps `.idea` folder can be added

There was a lot of issues filled for that in PHPStorm's Youtrack (https://youtrack.jetbrains.com/issues/WI?q=%22multiple%20definitions%22). But it's either marked as duplicate of this: https://youtrack.jetbrains.com/issue/WI-33965 (with 46 upvotes)  or it's fixed by manually excluding files or directories in vendor.
It doesn't seem like it's gonna move from PHPStorm side anytime soon.

Feel free to close the issue as this one was about file extensions, I'll open an other one if a new solution presents itself

**Comment by weirdan** [comment]
> Do you know that, if you use PHPStorm, you can add any extension to the list of file that must be read as PHP? 

This is kinda irrelevant, as I don't use PHPStorm.

It's all going to be fixed eventually by removing stubs from the plugin, maybe even deprecating the plugin itself when all of the required annotations move to Doctrine source files. This has already happened with collections, and there are requests for other doctrine parts.
