### ISSUE TITLE
Lot of problems when using this plugin with PHPStorm and writing Doctrine Repository

### ISSUE THREAD

**Issue by ostrolucky** [weirdan/doctrine-psalm-plugin#60]
Problem 1:
Bogus error
![Screenshot 2020-06-20 at 13 42 54](https://user-images.githubusercontent.com/496233/85201018-4f4a6600-b2fc-11ea-9998-f4f91cc2f9ee.png)

Problem 2:
Most of the methods missing in autocomplete. I mean methods such as `createQueryBuilder()`
![Screenshot 2020-06-20 at 13 43 04](https://user-images.githubusercontent.com/496233/85201105-0fd04980-b2fd-11ea-944e-362339d26882.png)

Problem 3:
Duplicate definition, this probably root reason why problem 1 and 2 happens:
![Screenshot 2020-06-20 at 13 43 17](https://user-images.githubusercontent.com/496233/85201122-2e364500-b2fd-11ea-932c-96c9e203f185.png)

Problem is not solved by exluding the plugin folder
![Screenshot 2020-06-20 at 13 44 13](https://user-images.githubusercontent.com/496233/85201132-38f0da00-b2fd-11ea-8c94-c3789b2b6326.png)

These results are after invalidating the cache.

**Comment by weirdan** [comment]
Related: #43 & #18

**Comment by ostrolucky** [comment]
Indeed. So workaround in my case is to mark EntityRepository in your plugin as plain text.

**Comment by weirdan** [comment]
This should be improved in [0.11.3](https://github.com/weirdan/doctrine-psalm-plugin/releases)
