### ISSUE TITLE
InvalidArgument false-positive

### ISSUE THREAD

**Issue by fluffycondor** [weirdan/doctrine-psalm-plugin#70]
InvalidArgument - src/Repository/SomethingRepository.php:20:29 - Argument 1 of Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository::__construct expects Doctrine\Common\Persistence\ManagerRegistry, Doctrine\Persistence\ManagerRegistry provided

Doctrine\Common\Persistence\ManagerRegistry has been moved to Doctrine\Persistence\ManagerRegistry namespace.

**Comment by weirdan** [comment]
`Doctrine\Common\Persistence\ManagerRegistry` deprecated as of `doctrine/persistence:1.3` and removed in `doctrine/persistence:2.0`
