### ISSUE TITLE
@psalm-mutation-free & isEmpty

### ISSUE THREAD

**Issue by mrVrAlex** [weirdan/doctrine-psalm-plugin#97]
Any collection which extends ArrayCollection produce error:
`ERROR: MissingImmutableAnnotation - src/Sales/Domain/Collection/ReturnItemCollection.php:20:7 - Doctrine\Common\Collections\Collection::isEmpty is marked @psalm-immutable, but Doctrine\Common\Collections\ArrayCollection::isEmpty is not marked @psalm-immutable (see https://psalm.dev/213)
class ReturnItemCollection extends ArrayCollection implements JsonSerializable
`

**Comment by orklah** [comment]
@VincentLanglet can you have a look? It looks like we should extend some change to childs of Collection

**Comment by weirdan** [comment]
@shandyDev does this also happen with this plugin disabled?

**Comment by orklah** [comment]
@weirdan this is most likely a side-effect of #94 who added a @psalm-mutation-free to Collection::isEmpty

**Comment by weirdan** [comment]
Ah, I was looking at the wrong branch it appears.

**Comment by mrVrAlex** [comment]
> does this also happen with this plugin disabled?

Of course no. Plugin apply stub for collection where method mark as @psalm-mutation-free  BUT in Doctrine libs ArrayCollection do not mark method as @psalm-mutation-free 
Anyway stub ArrayCollection in plugin not activated if

`        if ($this->hasPackageOfVersion('doctrine/collections', '>= 1.6.0')) {`

**Comment by VincentLanglet** [comment]
> @VincentLanglet can you have a look? It looks like we should extend some change to childs of Collection

Since there is a check 
```
if ($this->hasPackageOfVersion('doctrine/collections', '>= 1.6.0')) {
```
updating the arrayCollection stub won't solve everything.

The `psalm-mutation-free` "hack" should be added to doctrine/collections with some comment about why it's needed or our stub should be still used for package >= 1.6.0.
The second solution seems better to me @orklah ; not sure why the stub is removed for recent versions.
For the first solution we should see with @greg0ire

**Comment by orklah** [comment]
the first solution would mean a false annotation would be added to everyone and the behaviour would only be fixed for this plugin's users, this is not a possibility.

I'm all for having a stub for old versions of doctrine collections though

**Comment by weirdan** [comment]
> not sure why the stub is removed for recent versions.

At one point `doctrine/collections` must have reached typing parity with the stub in question, so I thought I would phase the stub out. If there's a mutual dependency between the hook and the stub, then the stub needs to be loaded unconditionally I think.

**Comment by VincentLanglet** [comment]
If we do this for ArrayCollection, we'll have to do it for every Collection implementation.
And people will also need to add the annotation to his implementation.

Maybe the best solution could be to introduce some listener like https://github.com/psalm/psalm-plugin-symfony/blob/master/src/Handler/AnnotationHandler.php#L10 to automatically add the annotation and/or suppress the issue ?
Don't really know how this works.

**Comment by orklah** [comment]
Is there a lot of Collection implementations? Stubs are easier to grasp than plugin so I'd prefer that if there's not too much of them

**Comment by enumag** [comment]
> Is there a lot of Collection implementations?

Doctrine itself only has 3 implementations:
- ArrayCollection
- PersistentCollection
- LazyCriteriaCollection

In my opinion adding stubs for these 3 will be both easier to do and easier to understand.

**Comment by orklah** [comment]
@VincentLanglet could we maybe add the annotation on those three?

**Comment by enumag** [comment]
There is also AbstractLazyCollection which is abstract as the name suggests... iirc PersistentCollection and LazyCriteriaCollection extend it.

**Comment by VincentLanglet** [comment]
Does https://github.com/psalm/psalm-plugin-doctrine/pull/99 solve the issue ?

**Comment by orklah** [comment]
Closing this as stale (and possibly fixed?)
